repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
    -   id: end-of-file-fixer
        files: ^tf|-|\.(py|env|yml|yaml|pem|key|mock)$
    -   id: detect-private-key
        files: ^(?!\.?git-crypt)
        exclude: ^docker/templates/id_rsa$
    -   id: check-merge-conflict
        files: ^tf|-|\.(py|tfvars|tf|tfenv|env|yml|yaml|pem|key|mock)$
    -   id: check-added-large-files
        files: ^tf|-|\.(py|env|yml|yaml)$
    -   id: check-case-conflict
    -   id: check-json
        language_version: python3
    -   id: check-xml
        language_version: python3
    -   id: check-yaml
        language_version: python3
    -   id: check-case-conflict
    -   id: check-ast
        language_version: python3
    -   id: check-docstring-first
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
        args: ['--django']
    -   id: file-contents-sorter
    -   id: sort-simple-yaml
    -   id: flake8
        files: ^src/.*\.py$
        args:
        - --max-line-length=80
        - --diff
        - --exclude=docs,migrations
-   repo: https://github.com/pre-commit/mirrors-pylint.git
    rev: v2.3.1
    hooks:
    -   id: pylint
        language_version: python3
        exclude: ^migrations/.*\.py$
        args:
        - --rcfile=.pylintrc
        - --errors-only
        - --disable=no-name-in-module,import-error,no-member
        - --ignore=settings_test, migrations
-   repo: https://github.com/FalconSocial/pre-commit-python-sorter.git
    rev: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
        language_version: python3
-   repo: https://github.com/detailyang/pre-commit-shell.git
    rev: 1.0.4
    hooks:
    -   id: shell-lint
        exclude: ^script/wait-for-it.sh$
        args:
        - --exclude=SC1072,SC1073,SC2068
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
        args:
        - -i
        - --ignore=E501
        language_version: python3
